version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install --upgrade pytest pytest-mock pandas
  build:
    commands:
      - echo 'Running unit tests'
      - make unit_test
